#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, int64_t C, int64_t K, const std::vector<int64_t> &D, const std::vector<int64_t> &V) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N;
    int64_t C, K;
    std::cin >> N;
    std::vector<int64_t> D(N), V(N);
    std::cin >> C >> K;
    REP (i, N) {
        std::cin >> D[i] >> V[i];
    }
    auto ans = solve(N, C, K, D, V);
    std::cout << ans << '\n';
    return 0;
}
