#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, const std::vector<int64_t> &T, int M, const std::vector<int64_t> &P, const std::vector<int64_t> &X) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    std::cin >> N;
    std::vector<int64_t> T(N);
    REP (i, N) {
        std::cin >> T[i];
    }
    std::cin >> M;
    std::vector<int64_t> P(M), X(M);
    REP (i, M) {
        std::cin >> P[i] >> X[i];
    }
    auto ans = solve(N, T, M, P, X);
    REP (i, M) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
