#!/usr/bin/env python3
# from typing import *


# def solve(N: int, T: List[int], M: int, P: List[int], X: List[int]) -> List[str]:
def solve(N, T, M, P, X):
    total = sum(T)

    for i in range(M):
        ans = total
        ans -= T[P[i] - 1]
        ans += X[i]
        print(ans)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    T = [None for _ in range(N)]
    for i in range(N):
        T[i] = int(next(tokens))
    M = int(next(tokens))
    P = [None for _ in range(M)]
    X = [None for _ in range(M)]
    for i in range(M):
        P[i] = int(next(tokens))
        X[i] = int(next(tokens))
    assert next(tokens, None) is None
    solve(N, T, M, P, X)


if __name__ == '__main__':
    main()
