#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> Any:
def solve(N):
    s = ""
    for i in range(1, N + 1):
        if i == 1:
            s = "1"
        else:
            s = f"{s} {i} {s}"
    print(s)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    ans = solve(N)


if __name__ == '__main__':
    main()
