#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str, T: str) -> str:
def solve(N, S, T):


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S, T = input().split()
    a = solve(N, S, T)
    print(a)


if __name__ == '__main__':
    main()
