#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(N: int, K: int) -> List[str]:
def solve(N, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    a = solve(N, K)
    for i in range(K):
        print(a[i])


if __name__ == '__main__':
    main()
