#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, K: int) -> Any:
def solve(A, B, K):
    for i in range(A, min([A + K, B])):
        print(i)

    for i in range(max([B - K + 1, A]), B + 1):
        if min([A + K, B]) <= i:
            print(i)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, K = map(int, input().split())
    solve(A, B, K)


if __name__ == '__main__':
    main()
