#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(w: str) -> str:
def solve(w):
    for s in w:
        if w.count(s) % 2 != 0:
            return NO
    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    w = input()
    a = solve(w)
    print(a)


if __name__ == '__main__':
    main()
