#!/usr/bin/env python3
# from typing import *


# def solve(Q: int, X: List[int], Y: List[int], A: List[int], B: List[int]) -> List[str]:
def solve(Q, X, Y, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = int(input())
    X = [None for _ in range(Q)]
    Y = [None for _ in range(Q)]
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        X[i], Y[i], A[i], B[i] = map(int, input().split())
    a = solve(Q, X, Y, A, B)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
