#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, W: List[int], L: List[int]) -> List[str]:
def solve(N, M, W, L):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    W = [None for _ in range(M)]
    L = [None for _ in range(M)]
    for i in range(M):
        W[i], L[i] = map(int, input().split())
    A = solve(N, M, W, L)
    print(*[A[i] for i in range(K)])


if __name__ == '__main__':
    main()
