#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> int:
def solve(N, A):
    cnt = 0
    while True:
        odd = False
        for i, v in enumerate(A):
            if v % 2 == 1:
                return cnt
            tmp = v // 2
            if tmp % 2 == 1:
                odd = True
                break
            A[i] = tmp
        cnt += 1
        if odd:
            return cnt


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A)
    print(a)


if __name__ == '__main__':
    main()
