#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int) -> int:
import math


def solve(A, B):
    ans = None
    for i in range(1, 10001):
        if A == math.floor(i * 0.08) and B == math.floor(i * 0.1):
            ans = i
            break

    if ans == None:
        return -1
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    a = solve(A, B)
    print(a)


if __name__ == '__main__':
    main()
