#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


def is_sequence(N, S):
    # 6つの連続したマスが存在するかどうか判定する
    horizontal = 0
    vertical = 0
    diagonal = 0

    for i in range(N):
        for j in range(N):
            # 横一列に連続した4つのマスが存在するか
            if (S[i][j] == "#"):
                horizontal += 1
            else:
                # 連続しなかった場合は0にリセットする
                horizontal = 0

            # 縦一列に連続した4つのマスが存在するか
            if (S[j][i] == "#"):
                vertical += 1
            else:
                # 連続しなかった場合は0にリセットする
                vertical = 0

            # 斜め一列に連続した4つのマスが存在するか
            if (S[j][j] == "#"):
                diagonal += 1
            else:
                # 連続しなかった場合は0にリセットする
                diagonal = 0
            # 4つ以上連続した場合は2つ埋めて6つ以上になるのでYESを出力する
            if (3 < horizontal or 3 < vertical or 3 < diagonal):
                return True
    return False


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    if (is_sequence(N, S)):
        return YES
    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input().rstrip())
    S = []
    for _ in range(N):
        S.append(list(input().rstrip()))
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
