#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int, K: int) -> int:
def solve(H, W, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, K = map(int, input().split())
    a = solve(H, W, K)
    print(a)


if __name__ == '__main__':
    main()
