#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(auto N, auto M, const std::vector<auto> &u, const std::vector<auto> &v, auto S, auto T) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M, S, T;
    std::cin >> N >> M;
    std::vector<auto> u(M), v(M);
    REP (i, M) {
        std::cin >> u[i] >> v[i];
    }
    std::cin >> S >> T;
    auto ans = solve(N, M, u, v, S, T);
    std::cout << ans << '\n';
    return 0;
}
