#!/usr/bin/env python3
# from typing import *


# def solve(N: str, M: str, u: List[str], v: List[str], S: str, T: str) -> int:
def solve(N, M, u, v, S, T):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = input().split()
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = input().split()
    S, T = input().split()
    a = solve(N, M, u, v, S, T)
    print(a)


if __name__ == '__main__':
    main()
