#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int]) -> List[str]:
import copy


def solve(N, A):
    l = copy.copy(A)
    l.sort()
    maxInt = l[-1]
    for i in range(N):
        if A[i] == maxInt:
            print(l[-2])
        else:
            print(maxInt)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(input())
    solve(N, A)


if __name__ == '__main__':
    main()
