#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, K: int, L: int, A: List[int], B: List[int], U: List[int], V: List[int], C: List[int]) -> List[str]:
def solve(N, M, K, L, A, B, U, V, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    K = int(next(tokens))
    L = int(next(tokens))
    A = [None for _ in range(N)]
    B = [None for _ in range(L)]
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    C = [None for _ in range(M)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(L):
        B[i] = int(next(tokens))
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
        C[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, M, K, L, A, B, U, V, C)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
