#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


def isSequence(N, S):
    # 6つの連続したマスが存在するかどうか判定する
    row = 0
    line = 0
    for i in range(N):
        for j in range(N):
            # 横一列に連続した6つのマスが存在するか
            if (S[i][j] == "#"):
                row += 1
            else:
                # 連続しなかった場合は0にリセットする
                row = 0

            # 縦一列に連続した6つのマスが存在するか
            if (S[j][i] == "#"):
                line += 1
            else:
                # 連続しなかった場合は0にリセットする
                line = 0

            if (row == 6 or line == 6):
                return True
    return False


# def solve(N: int, S: List[str]) -> str:
def solve(N, S):
    return isSequence(N, S)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    stdin = open("in.txt")
    N = int(stdin.readline().rstrip())
    S = []
    for _ in range(N):
        S.append(list(stdin.readline().rstrip()))
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
