#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Tuple[int, int, int, int, int, int]:
from template.SortedMultiset import SortedMultiset


def solve(N, Q):
    A = SortedMultiset()
    for i in range(N):
        x = Q[i][1]

        if Q[i][0] == 1:
            # A に x を追加する。
            A.add(x)
        if Q[i][0] == 2:
            # x 以下の要素のうち、大きい方から k 番目の値を出力する
            k = Q[i][2]
            p = A.index_right(x) - k
            if p < 0:
                print(-1)
            else:
                print(A[p])

        if Q[i][0] == 3:
            k = Q[i][2]
            p = len(A) - A.index(x) - k

            if p < 0:
                print(-1)
            else:
                print(A[~p])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    stdin = open('in.txt')
    # failed to analyze input format
    N = int(stdin.readline())  # TODO: edit here
    Q = [list(map(int, stdin.readline().split())) for Q in range(N)]
    solve(N, Q)


if __name__ == '__main__':
    main()
