#!/usr/bin/env python3
# from typing import *
import itertools

MOD = 998244353


# def solve(N: int, M: int, K: int) -> int:
def solve(N, M, K):
    l = list(itertools.permutations([i for i in range(1, M + 1)], N))
    return len(l) % MOD


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = map(int, input().split())
    a = solve(N, M, K)
    print(a)


if __name__ == '__main__':
    main()
