#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(n: int, k: int) -> int:
def solve(n, k):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n, k = map(int, input().split())
    a = solve(n, k)
    print(a)


if __name__ == '__main__':
    main()
