#!/usr/bin/env python3
# from typing import *


# def solve(X: int) -> int:
def solve(X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = int(input())
    a = solve(X)
    print(a)


if __name__ == '__main__':
    main()
