#!/usr/bin/env python3
# from typing import *


# def solve(X: int, Y: int, Z: int) -> Tuple[int, int, int]:
def solve(X, Y, Z):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y, Z = map(int, input().split())
    d, e, f = solve(X, Y, Z)
    print(d, e, f)


if __name__ == '__main__':
    main()
