#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: List[str], c: List[str], d: List[List[str]], e: str) -> int:
def solve(N, M, K):
    cnt = 0
    for i in range(M + 1):
        is_like = True
        # Mの値が全員の配列の中に含まれているかどうか
        for j in range(N):
            if i not in K[j]:
                is_like = False
        if is_like:
            cnt += 1
    print(cnt)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    K = [None for _ in range(N)]
    for i in range(N):
        K[i] = list(map(int, input().split()[1:]))

    solve(N, M, K)


if __name__ == '__main__':
    main()
