#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> int:
def solve(S):
    S = list(S)
    cnt = 0
    for i in range(len(S) - 1):
        if S[i] == S[i + 1]:
            # 白白
            if S[i] == "1":
                S[i + 1] = "0"
                cnt += 1
            else:
                # 黒黒
                S[i + 1] = "1"
                cnt += 1

    return cnt


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
