#!/usr/bin/env python3
# from typing import *


# def solve(S: str, Q: str, Query: List[str]) -> str:
def solve(S, Q, Query):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    Q = input()
    Query = [None for _ in range(Q)]
    for i in range(Q):
        Query[i] = input()
    a = solve(S, Q, Query)
    print(a)


if __name__ == '__main__':
    main()
