#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, u: List[int], v: List[int]) -> int:
def solve(N, M, u, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = map(int, input().split())
    a = solve(N, M, u, v)
    print(a)


if __name__ == '__main__':
    main()
