#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(x: int, y: int) -> str:
def solve(x, y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    x, y = map(int, input().split())
    a = solve(x, y)
    print(a)


if __name__ == '__main__':
    main()
