#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    c = [[None for _ in range(10)] for _ in range(10)]
    H = random.randint(1, 1000)  # TODO: edit here
    W = random.randint(1, 1000)  # TODO: edit here
    A = [[None for _ in range(W)] for _ in range(H)]
    for j in range(10):
        for i in range(10):
            c[j][i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for j in range(H):
        for i in range(W):
            A[j][i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(H, W)
    for j in range(10):
        print(*[c[j][i] for i in range(10)])
    for j in range(H):
        print(*[A[j][i] for i in range(W)])


if __name__ == "__main__":
    main()
