#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int H, int W, const std::vector<std::vector<int64_t> > &c, const std::vector<std::vector<int64_t> > &A) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int H, W;
    std::vector<std::vector<int64_t> > c(10, std::vector<int64_t>((10)));
    std::cin >> H >> W;
    std::vector<std::vector<int64_t> > A(H, std::vector<int64_t>((W)));
    REP (j, 10) {
        REP (i, 10) {
            std::cin >> c[j][i];
        }
    }
    REP (j, H) {
        REP (i, W) {
            std::cin >> A[j][i];
        }
    }
    auto ans = solve(H, W, c, A);
    std::cout << ans << '\n';
    return 0;
}
