#!/usr/bin/env python3
# from typing import *


# def solve(N: str, S: str, Q: str, Query: List[str]) -> Tuple[int, int, int]:
def solve(N, S, Q, Query):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = input()
    S = input()
    Q = input()
    Query = [None for _ in range(Q)]
    for i in range(Q):
        Query[i] = input()
    a, b, c = solve(N, S, Q, Query)
    print(a)
    print(b)
    print(c)


if __name__ == '__main__':
    main()
