#!/usr/bin/env python3
# from typing import *


# def solve(N: int, d: List[int]) -> int:
def solve(N, d):
    d.sort()
    _from = d[N // 2 - 1]
    _to = d[N // 2]

    return _to - _from


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    d = [None for _ in range(N)]
    for i in range(N):
        d[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, d)
    print(a)


if __name__ == '__main__':
    main()
