#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(auto N, auto M, auto K, const std::vector<auto> &A, const std::vector<auto> &B, const std::vector<auto> &C, const std::vector<auto> &D) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M, K;
    std::cin >> N >> M;
    std::vector<auto> A(M), B(M);
    std::cin >> K;
    std::vector<auto> C(K), D(K);
    REP (i, M) {
        std::cin >> A[i] >> B[i];
    }
    REP (i, K) {
        std::cin >> C[i] >> D[i];
    }
    auto ans = solve(N, M, K, A, B, C, D);
    // failed to analyze output format
    // TODO: edit here
    std::cout << ans << '\n';
    return 0;
}
