#!/usr/bin/env python3
# from typing import *


# def solve(N: str, M: str, K: str, A: List[str], B: List[str], C: List[str], D: List[str]) -> Any:
def solve(N, M, K, A, B, C, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = input().split()
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    C = [None for _ in range(K)]
    D = [None for _ in range(K)]
    for i in range(M):
        A[i], B[i] = input().split()
    for i in range(K):
        C[i], D[i] = input().split()
    ans = solve(N, M, K, A, B, C, D)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
