#!/usr/bin/env python3
# from typing import *


def solve(a, b, c, d):
    x = c - a
    y = d - b
    print(*[c - y, d + x, a - y, b + x])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c, d = map(int, input().split())  # TODO: edit here
    solve(a, b, c, d)


if __name__ == '__main__':
    main()
