#!/usr/bin/env python3
# from typing import *


# def solve(T: str, case: List[str]) -> Any:
def solve(T, case):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = input()
    case = [None for _ in range(T)]
    for i in range(T):
        case[i] = input()
    ans = solve(T, case)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
