#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 1000000007;
int64_t solve(int n, int m, const std::vector<int64_t> &x, const std::vector<int64_t> &y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int n, m;
    std::cin >> n;
    std::vector<int64_t> x(n);
    std::cin >> m;
    std::vector<int64_t> y(m);
    REP (i, n) {
        std::cin >> x[i];
    }
    REP (i, m) {
        std::cin >> y[i];
    }
    auto ans = solve(n, m, x, y);
    std::cout << ans << '\n';
    return 0;
}
