#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(n: int, m: int, x: List[int], y: List[int]) -> int:
def solve(n, m, x, y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    n = int(next(tokens))
    m = int(next(tokens))
    x = [None for _ in range(n)]
    y = [None for _ in range(m)]
    for i in range(n):
        x[i] = int(next(tokens))
    for i in range(m):
        y[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(n, m, x, y)
    print(a)


if __name__ == '__main__':
    main()
