#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, a: List[int], b: List[int], p: List[int], x: List[int]) -> List[str]:
def solve(N, Q, a, b, p, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    a = [None for _ in range(N - 1)]
    b = [None for _ in range(N - 1)]
    p = [None for _ in range(Q)]
    x = [None for _ in range(Q)]
    for i in range(N - 1):
        a[i], b[i] = map(int, input().split())
    for i in range(Q):
        p[i], x[i] = map(int, input().split())
    ans = solve(N, Q, a, b, p, x)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
