#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


std::vector<auto> solve(int N, int Q, const std::vector<int64_t> &a, const std::vector<int64_t> &b, const std::vector<int64_t> &p, const std::vector<int64_t> &x) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, Q;
    std::cin >> N;
    std::vector<int64_t> a(N - 1), b(N - 1);
    std::cin >> Q;
    std::vector<int64_t> p(Q), x(Q);
    REP (i, N - 1) {
        std::cin >> a[i] >> b[i];
    }
    REP (i, Q) {
        std::cin >> p[i] >> x[i];
    }
    auto ans = solve(N, Q, a, b, p, x);
    REP (i, (int)ans.size()) {
        std::cout << ans[i] << ' ';
    }
    std::cout << '\n';
    return 0;
}
