#!/usr/bin/env python3
# from typing import *


# def solve(n: int, s: int) -> int:
def solve(n, s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    s = int(input())
    a = solve(n, s)
    print(a)


if __name__ == '__main__':
    main()
