#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(a: str, b: List[str], c: List[str], d: str) -> int:
def solve(a, b, c, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = [None for _ in range(a)]
    c = [None for _ in range(a)]
    for i in range(a):
        b[i] = next(tokens)
        c[i] = next(tokens)
    d = next(tokens)
    assert next(tokens, None) is None
    a1 = solve(a, b, c, d)
    print(a1)


if __name__ == '__main__':
    main()
