#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    M = random.randint(1, 1000)  # TODO: edit here
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    K = random.randint(1, 10 ** 9)  # TODO: edit here
    S = random.randint(1, 10 ** 9)  # TODO: edit here
    T = random.randint(1, 10 ** 9)  # TODO: edit here
    X = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(M):
        U[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        V[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, M, K, S, T, X)
    for i in range(M):
        print(U[i], V[i])


if __name__ == "__main__":
    main()
