#!/usr/bin/env python3
# from typing import *


# def solve(s: str, t: str) -> int:
def solve(s, t):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    t = input()
    a = solve(s, t)
    print(a)


if __name__ == '__main__':
    main()
