#!/usr/bin/env python3
# from typing import *


# def solve(Q: int, A: List[int], B: List[int]) -> Tuple[str, List[str], List[str], str, str, str]:
def solve(Q, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = int(input())
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        A[i], B[i] = map(int, input().split())
    g, h, m, n, o, p = solve(Q, A, B)
    print(g)
    for i in range(g):
        print(h[i])
        print(m[i])
    print(n)
    print(o)
    print(p)


if __name__ == '__main__':
    main()
