#!/usr/bin/env python3
# from typing import *


# def solve(N: int, R: int) -> int:
def solve(N, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, R = map(int, input().split())
    a = solve(N, R)
    print(a)


if __name__ == '__main__':
    main()
