#!/usr/bin/env python3
# from typing import *


# def solve(H: str, W: str, C: List[List[str]]) -> Any:
def solve(H, W, C):
    for i in range(H):
        print(C[i])
        print(C[i])


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    H = int(next(tokens))
    W = int(next(tokens))
    C = [None for _ in range(H)]
    for i in range(H):
        C[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(H, W, C)


if __name__ == '__main__':
    main()
