#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, a: List[int], b: List[int], c: List[int], d: List[int], x: List[int], y: List[int], u: List[int], v: List[int]) -> List[str]:
def solve(N, Q, a, b, c, d, x, y, u, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    a = [None for _ in range(N - 1)]
    b = [None for _ in range(N - 1)]
    c = [None for _ in range(N - 1)]
    d = [None for _ in range(N - 1)]
    x = [None for _ in range(Q)]
    y = [None for _ in range(Q)]
    u = [None for _ in range(Q)]
    v = [None for _ in range(Q)]
    for i in range(N - 1):
        a[i], b[i], c[i], d[i] = map(int, input().split())
    for i in range(Q):
        x[i], y[i], u[i], v[i] = map(int, input().split())
    e = solve(N, Q, a, b, c, d, x, y, u, v)
    for i in range(Q):
        print(e[i])


if __name__ == '__main__':
    main()
