#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, int Q, const std::vector<int64_t> &a, const std::vector<int64_t> &b, const std::vector<int64_t> &c, const std::vector<int64_t> &d, const std::vector<int64_t> &x, const std::vector<int64_t> &y, const std::vector<int64_t> &u, const std::vector<int64_t> &v) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, Q;
    std::cin >> N;
    std::vector<int64_t> a(N - 1), b(N - 1), c(N - 1), d(N - 1);
    std::cin >> Q;
    std::vector<int64_t> x(Q), y(Q), u(Q), v(Q);
    REP (i, N - 1) {
        std::cin >> a[i] >> b[i] >> c[i] >> d[i];
    }
    REP (i, Q) {
        std::cin >> x[i] >> y[i] >> u[i] >> v[i];
    }
    auto ans = solve(N, Q, a, b, c, d, x, y, u, v);
    REP (i, Q) {
        std::cout << e[i] << '\n';
    }
    return 0;
}
