#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(n: int, a: List[int]) -> str:
def solve(n, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    bingo = [list(map(int, input().split())) for _ in range(3)]
    N = int(input())
    S = []
    for _ in range(N):
        S.append(int(input()))

    for i in range(3):
        for j in range(3):
            if bingo[i][j] in S:
                bingo[i][j] = "#"

    def calc(x, y, dx, dy):
        count = 0
        for _ in range(3):
            if not (0 <= min(x, y) and max(x, y) < 3):
                continue
            if bingo[x][y] == '#':
                count += 1
            x += dx
            y += dy
        # ビンゴしているか
        return 3 == count

    Dx = [1, 0, 1, 1]
    Dy = [0, 1, 1, -1]
    for x in range(N):
        for y in range(N):
            for dx, dy in zip(Dx, Dy):
                if calc(x, y, dx, dy):
                    print(YES)
                    return
    print(NO)


if __name__ == '__main__':
    main()
