#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, S: str) -> str:
def solve(N, K, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    S = input()
    a = solve(N, K, S)
    print(a)


if __name__ == '__main__':
    main()
