#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(N: int, P: int) -> List[str]:
def solve(N, P):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, P = map(int, input().split())
    a = solve(N, P)
    print(*[a[i] for i in range(N)])


if __name__ == '__main__':
    main()
