#!/usr/bin/env python3
# from typing import *

YES = 'Possible'
NO = 'Impossible'


# def solve(N: int, L: int, a: List[int]) -> Any:
def solve(N, L, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    L = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, L, a)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
