#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, c: int, d: int, e: int, k: int) -> str:
def solve(a, b, c, d, e, k):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b = int(input())
    c = int(input())
    d = int(input())
    e = int(input())
    k = int(input())
    a1 = solve(a, b, c, d, e, k)
    print(a1)


if __name__ == '__main__':
    main()
