#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, a: List[int], b: List[int], Q: int, x: List[int], y: List[int], z: List[int]) -> List[str]:
def solve(N, M, a, b, Q, x, y, z):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    for i in range(M):
        a[i], b[i] = map(int, input().split())
    Q = int(input())
    x = [None for _ in range(Q)]
    y = [None for _ in range(Q)]
    z = [None for _ in range(Q)]
    for i in range(Q):
        x[i], y[i], z[i] = map(int, input().split())
    ans = solve(N, M, a, b, Q, x, y, z)
    for i in range(M):
        print(ans[i])


if __name__ == '__main__':
    main()
