#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int64_t N, int M, const std::vector<int64_t> &a, const std::vector<int64_t> &b, int Q, const std::vector<int64_t> &x, const std::vector<int64_t> &y, const std::vector<int64_t> &z) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N;
    int M, Q;
    std::cin >> N >> M;
    std::vector<int64_t> a(M), b(M);
    REP (i, M) {
        std::cin >> a[i] >> b[i];
    }
    std::cin >> Q;
    std::vector<int64_t> x(Q), y(Q), z(Q);
    REP (i, Q) {
        std::cin >> x[i] >> y[i] >> z[i];
    }
    auto ans = solve(N, M, a, b, Q, x, y, z);
    REP (i, M) {
        std::cout << ans[i] << '\n';
    }
    return 0;
}
