#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = random.randint(1, 1000)  # TODO: edit here
    b = [None for _ in range(a)]
    for i in range(a):
        b[i] = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    c = random.randint(1, 1000)  # TODO: edit here
    d = [None for _ in range(c)]
    e = [None for _ in range(c)]
    for i in range(c):
        d[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        e[i] = ''.join([random.choice('abcde') for _ in range(random.randint(1, 100))])  # TODO: edit here
    print(a)
    for i in range(a):
        print(b[i])
    print(c)
    for i in range(c):
        print(d[i], e[i])


if __name__ == "__main__":
    main()
