#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int a, const std::vector<std::string> &b, int c, const std::vector<int64_t> &d, const std::vector<std::string> &e) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int a, c;
    std::cin >> a;
    std::vector<std::string> b(a);
    REP (i, a) {
        std::cin >> b[i];
    }
    std::cin >> c;
    std::vector<int64_t> d(c);
    std::vector<std::string> e(c);
    REP (i, c) {
        std::cin >> d[i] >> e[i];
    }
    auto ans = solve(a, b, c, d, e);
    REP (i, c) {
        std::cout << f[i] << '\n';
    }
    return 0;
}
