#!/usr/bin/env python3
# from typing import *

MOD = 998244353
YES = 'Yes'
NO = 'No'


# def solve(H: str, W: str, C: List[List[str]]) -> Tuple[str, str, str]:
def solve(H, W, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    H = next(tokens)
    W = next(tokens)
    C = [[None for _ in range(H + W + 4)] for _ in range(H + W + 4)]
    for j in range(H + 4):
        for i in range(W):
            C[i + j][i + j] = next(tokens)
    assert next(tokens, None) is None
    Yes, n, r = solve(H, W, C)
    print(Yes)
    print(n, r)


if __name__ == '__main__':
    main()
