#!/usr/bin/env python3
# from typing import *

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    max_num = 2 * N + 1

    l = []
    for i in range(1, max_num + 1):
        l.append(i)

    for i in range(max_num):
        print(l.pop(), flush=True)
        if (len(l) == 0):
            exit()
        ans = int(input())
        l.remove(ans)


if __name__ == '__main__':
    main()
