#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(n: int, a: int, b: int) -> int:
def solve(n, a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n, a, b = map(int, input().split())
    a1 = solve(n, a, b)
    print(a1)


if __name__ == '__main__':
    main()
