#!/usr/bin/env python3
# from typing import *


# def solve(N: int, v: List[int]) -> float:
def solve(N, v):
    while True:
        v.sort(reverse=True)
        a = v.pop()
        b = v.pop()
        v.append((a + b) / 2)
        if len(v) == 1:
            return v.pop()


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    v = [None for _ in range(N)]
    for i in range(N):
        v[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, v)
    print(a)


if __name__ == '__main__':
    main()
