#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int) -> int:
def solve(H, W):
    board = []
    for i in range(H):
        board.append([])
        for j in range(W):
            board[i].append(".")

    def calc(x, y, dx, dy):
        if (0 <= min(x, y) and max(x, y) < W):
            board[x][y] = "#"
        x += dx
        y += dy

    Dx = [1, 1]
    Dy = [1, -1]
    for x in range(H):
        for y in range(W):
            for dx, dy in zip(Dx, Dy):
                calc(x, y, dx, dy)

    print(board)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    a = solve(H, W)
    print(a)


if __name__ == '__main__':
    main()
