#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int) -> int:


def solve(H, W):
    if H == 1 or W == 1:
        return 1

    if H * W % 2 == 0:
        return H * W // 2

    return H * W // 2 + 1


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    a = solve(H, W)
    print(a)


if __name__ == '__main__':
    main()
