#!/usr/bin/env python3
# from typing import *


# def solve(N: int) -> List[str]:
def solve(N):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    w = solve(N)
    for i in range(K):
        print(w[i])


if __name__ == '__main__':
    main()
