#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int) -> int:
def solve(N, A, B):
    total = 0
    for i in range(N + 1):
        X = sum([int(str(i)[j]) for j in range(len(str(i)))])
        if A <= X <= B:
            total += i

    return total


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    a = solve(N, A, B)
    print(a)


if __name__ == '__main__':
    main()
