#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int k, int q, const std::vector<int64_t> &d, const std::vector<int64_t> &n, const std::vector<int64_t> &x, const std::vector<int64_t> &m) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int k, q;
    std::cin >> k;
    std::vector<int64_t> d(k);
    std::cin >> q;
    std::vector<int64_t> n(q), x(q), m(q);
    REP (i, k) {
        std::cin >> d[i];
    }
    REP (i, q) {
        std::cin >> n[i] >> x[i] >> m[i];
    }
    auto ans = solve(k, q, d, n, x, m);
    REP (i, q) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
