#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, C: int, S: str) -> Any:
def solve(N, K, C, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K, C = map(int, input().split())
    S = input()
    ans = solve(N, K, C, S)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
