#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int) -> Tuple[int, int, List[str]]:
def solve(A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    n, k, a = solve(A, B)
    print(n, k)
    for i in range(n):
        print(a[i])


if __name__ == '__main__':
    main()
