#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: List[str]) -> Any:
def solve(N, S):
    cnt = dict()

    for v in S:
        if v not in cnt:
            cnt[v] = 1
        else:
            cnt[v] += 1

    sorted_dict = sorted(cnt.items(), key=lambda x: x[1], reverse=True)

    ans = []
    max = None
    for v in sorted_dict:
        if max is None:
            max = v[1]
        if max == v[1]:
            ans.append(v[0])
        else:
            continue

    for v in sorted(ans):
        print(v)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    ans = solve(N, S)


if __name__ == '__main__':
    main()
