#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, C: int, D: int, E: int) -> int:
def solve(A, B, C, D, E):
    last = A
    l = [A, B, C, D, E]

    # 1桁目が一番小さい値を取得
    for v in l:
        if v % 10 != 0:
            if int(str(v)[-1]) < int(str(last)[-1]):
                last = v

    last = l.pop(l.index(last))
    total = 0
    for v in l:
        if v % 10 == 0:
            total += v
        else:
            total += v + (10 - int(str(v)[-1]))
    return total + last


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = int(input())
    B = int(input())
    C = int(input())
    D = int(input())
    E = int(input())
    a = solve(A, B, C, D, E)
    print(a)


if __name__ == '__main__':
    main()
