#!/usr/bin/env python3
# from typing import *


# def solve(N: int, x: int, a: List[int]) -> int:
def solve(N, x, a):
    a.sort()

    cnt = 0
    for i in a:
        if i <= x and 0 <= x - i:
            x -= i
            cnt += 1
        else:
            return cnt

    if 0 < x:
        return cnt - 1
    return cnt


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    x = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(N, x, a)
    print(a1)


if __name__ == '__main__':
    main()
