#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> int:
def solve(S):
    N = len(S)
    dp = [[0, 0] for _ in [0] * N]
    dp[0][0] = 1
    dp[1][1] = 1

    for i in range(1, N):
        if S[i] != S[i - 1]:
            dp[i][0] = dp[i - 1][0] + 1
        dp[i][0] = max(dp[i][0], dp[i - 1][1] + 1)
        if i > 1:
            dp[i][1] = dp[i - 2][0] + 1
        if i > 2 and S[i - 1:i + 1] != S[i - 3:i - 1]:
            dp[i][1] = max(dp[i][1], dp[i - 2][1] + 1)
    print(max(dp[-1]))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)


if __name__ == '__main__':
    main()
