#!/usr/bin/env python3
# from typing import *


# def solve(V: int, A: int, B: int, C: int) -> str:
def solve(V, A, B, C):
    while (True):
        for v in ["A", "B", "C"]:
            if (v == "A"):
                V -= A
                if V < 0:
                    return "F"
            if (v == "B"):
                V -= B
                if V < 0:
                    return "M"
            if (v == "C"):
                V -= C
                if V < 0:
                    return "T"


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    V, A, B, C = map(int, input().split())
    a = solve(V, A, B, C)
    print(a)


if __name__ == '__main__':
    main()
