#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> int:
import math


def solve(N, D, A):
    cnt = 0
    for i in range(N):
        for j in range(i + 1, N):
            X = 0
            for k in range(D):
                X += (A[i][k] - A[j][k]) ** 2
            if math.sqrt(X).is_integer():
                cnt += 1

    return cnt


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, D = map(int, input().split())  # TODO: edit here
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = list(map(int, input().split()))  # TODO: edit here
    a = solve(N, D, a)
    print(a)


if __name__ == '__main__':
    main()
