#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, q: List[int]) -> List[str]:
def solve(N, Q, q):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    q = [None for _ in range(Q)]
    for i in range(Q):
        q[i] = int(input())
    ans = solve(N, Q, q)
    for i in range(N):
        print(ans[i])


if __name__ == '__main__':
    main()
