#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(n: int, a: List[int]) -> str:
def solve(N, S):
    cnt = 0
    for i in range(3):
        if N[i] == S[i]:
            cnt += 1
    if cnt == 1:
        return NO

    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = list(map(str, input().split()))
    S = list(map(str, input().split()))
    a = solve(N, S)
    print(a)


if __name__ == '__main__':
    main()
