#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, R: int, S: int, P: int, T: str) -> int:
def solve(N, K, R, S, P, T):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    R, S, P = map(int, input().split())
    T = input()
    a = solve(N, K, R, S, P, T)
    print(a)


if __name__ == '__main__':
    main()
