import numpy as np


# def solve(n: int, a: List[int]) -> Any:
def solve(N, M, A, B):
    b = np.poly1d(B) / np.poly1d(A)
    print(*list(map(int, b[0].coef)))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    # failed to analyze input format
    N, M = map(int, input().split())  # TODO: edit here
    A = list(map(int, input().split()))  # TODO: edit here
    B = list(map(int, input().split()))  # TODO: edit here
    ans = solve(N, M, A, B)


if __name__ == '__main__':
    main()
