#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(L: int, R: int) -> int:
def solve(L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    L, R = map(int, input().split())
    a = solve(L, R)
    print(a)


if __name__ == '__main__':
    main()
