#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int], B: List[int]) -> Tuple[int, int]:
def solve(N, A, B):
    ans1 = 0
    ans2 = 0
    for i in range(N):
        isExist = False
        for j in range(N):
            # AにもBにも含まれているか
            if (A[i] == B[j]):
                isExist = True
                continue
        # 位置が一致しているか
        if (isExist):
            if (A[i] == B[i]):
                ans1 += 1
            else:
                ans2 += 1
    return ans1, ans2


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(N):
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    c, d = solve(N, A, B)
    print(c)
    print(d)


if __name__ == '__main__':
    main()
