#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> str:
def solve(S):
    l = list(S)
    l.sort()
    return ''.join(l)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
