#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, A: int, B: int, S: str) -> List[str]:
def solve(N, A, B, S):
    # 予選通過者数
    qualifier = 0
    # 海外の予選通過者数
    abroad_qualifier = 0

    for s in S:
        if s == "c":
            print(NO)
        if s == "a":
            if qualifier < A + B:
                print(YES)
                qualifier += 1
            else:
                print(NO)
        if s == "b":
            if qualifier < A + B and abroad_qualifier < B:
                print(YES)
                qualifier += 1
                abroad_qualifier += 1
            else:
                print(NO)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    S = input()
    ans = solve(N, A, B, S)
    # for i in range(N):
    #     print(ans[i])


if __name__ == '__main__':
    main()
