#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int) -> int:
def solve(N, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = int(input())
    a = solve(N, A)
    print(a)


if __name__ == '__main__':
    main()
