#!/usr/bin/env python3
# from typing import *


# def solve(a: int, s: str) -> str:
def solve(a, s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    s = input()
    a1 = solve(a, s)
    print(a1)


if __name__ == '__main__':
    main()
