#!/usr/bin/env python3
# from typing import *


# def solve(A: int, P: int) -> int:
def solve(A, P):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, P = map(int, input().split())
    a = solve(A, P)
    print(a)


if __name__ == '__main__':
    main()
