#!/usr/bin/env python3
# from typing import *

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    S = set()
    max = 0
    ans = 0

    for i in range(N):
        work = next(tokens)
        score = int(next(tokens))

        if work not in S:
            if max < score:
                max = score
                ans = i + 1
        S.add(work)

    assert next(tokens, None) is None
    print(ans)


if __name__ == '__main__':
    main()
