#!/usr/bin/env python3
# from typing import *
import string

YES = 'Yes'
NO = 'No'


# def solve(S: str) -> str:
def solve(S):
    has_uppercase = False
    has_lowercase = False
    for i in range(len(S) - 1):
        for j in range(i + 1, len(S)):
            if S[i] == S[j]:
                return NO

            if S[i] in string.ascii_uppercase:
                has_uppercase = True

            if S[j] in string.ascii_lowercase:
                has_lowercase = True

    if has_uppercase and has_lowercase:
        return YES

    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
