#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, a: List[int], b: List[int]) -> List[str]:
def solve(N, M, a, b):
    for i in range(1, N + 1):
        cnt = 0
        for j in range(M):
            if a[j] == i:
                cnt += 1
            if b[j] == i:
                cnt += 1
        print(cnt)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    for i in range(M):
        a[i], b[i] = map(int, input().split())
    solve(N, M, a, b)


if __name__ == '__main__':
    main()
