#!/usr/bin/env python3
# from typing import *


# def solve(N: int, B: List[int]) -> int:
def solve(N, B):
    ans = B[0] + B[N - 2]
    for i in range(N - 2):
        ans += min(B[i], B[i + 1])

    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    B = [None for _ in range(N - 1)]
    for i in range(N - 1):
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, B)
    print(a)


if __name__ == '__main__':
    main()
