#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, x: List[int]) -> int:
def solve(N, K, x):
    total = 0
    for i in x:
        a = i * 2
        if (i < K):
            b = (K - i) * 2
        else:
            b = (i - K) * 2

        if (a < b):
            total += a
        else:
            total += b
    return total


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    x = [None for _ in range(N)]
    K = int(next(tokens))
    for i in range(N):
        x[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, x)
    print(a)


if __name__ == '__main__':
    main()
