#!/usr/bin/env python3
# from typing import *


# def solve(x: int) -> int:
def solve(x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    x = int(input())
    a = solve(x)
    print(a)


if __name__ == '__main__':
    main()
