#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, X: List[int], Y: List[int], S: str) -> str:
def solve(N, l, S):
    dic = {}
    for i in range(N):
        x = l[i][0]
        y = l[i][1]
        # 初期化
        try:
            if (dic[y] is None):
                None
        except:
            dic[y] = {"R": None, "L": None}

        # 右を向いている人のうち最も左のx座標にいる人、左を向いている人のうち最も右のx座標にいる人のみ取り出し
        if S[i] == "R":
            if (dic[y]["R"] == None or x < dic[y]["R"]):
                dic[y]["R"] = x
        if S[i] == "L":
            if (dic[y]["L"] == None or dic[y]["L"] < x):
                dic[y]["L"] = x

    for v in dic.values():
        if (v["R"] is not None and v["L"] is not None):
            # 人 p の x 座標が 人 q より小さい
            if (v["R"] < v["L"]):
                return YES
    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    l = [list(map(int, input().split())) for i in range(N)]
    S = input()
    a = solve(N, l, S)
    print(a)


if __name__ == '__main__':
    main()
