#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(X)]
    Y = random.randint(1, 1000)  # TODO: edit here
    B = [None for _ in range(Y)]
    Z = random.randint(1, 1000)  # TODO: edit here
    C = [None for _ in range(Z)]
    K = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(X):
        A[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(Y):
        B[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(Z):
        C[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(X, Y, Z, K)
    print(*[A[i] for i in range(X)])
    print(*[B[i] for i in range(Y)])
    print(*[C[i] for i in range(Z)])


if __name__ == "__main__":
    main()
