#!/usr/bin/env python3
# from typing import *


# def solve(X: int, Y: int, Z: int, K: int, A: List[int], B: List[int], C: List[int]) -> List[str]:
def solve(X, Y, Z, K, A, B, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    X = int(next(tokens))
    Y = int(next(tokens))
    Z = int(next(tokens))
    K = int(next(tokens))
    A = [None for _ in range(X)]
    B = [None for _ in range(Y)]
    C = [None for _ in range(Z)]
    for i in range(X):
        A[i] = int(next(tokens))
    for i in range(Y):
        B[i] = int(next(tokens))
    for i in range(Z):
        C[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(X, Y, Z, K, A, B, C)
    for i in range(K):
        print(a[i])


if __name__ == '__main__':
    main()
