#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int X, int Y, int Z, int64_t K, const std::vector<int64_t> &A, const std::vector<int64_t> &B, const std::vector<int64_t> &C) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int X, Y, Z;
    int64_t K;
    std::cin >> X;
    std::vector<int64_t> A(X);
    std::cin >> Y;
    std::vector<int64_t> B(Y);
    std::cin >> Z;
    std::vector<int64_t> C(Z);
    std::cin >> K;
    REP (i, X) {
        std::cin >> A[i];
    }
    REP (i, Y) {
        std::cin >> B[i];
    }
    REP (i, Z) {
        std::cin >> C[i];
    }
    auto ans = solve(X, Y, Z, K, A, B, C);
    REP (i, K) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
