#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(K: int, N: int, M: int) -> int:
def solve(K, N, M):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K, N, M = map(int, input().split())
    a = solve(K, N, M)
    print(a)


if __name__ == '__main__':
    main()
