#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(K: int, X: int) -> str:
def solve(K, X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K, X = map(int, input().split())
    a = solve(K, X)
    print(a)


if __name__ == '__main__':
    main()
