#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(a: str, b: str, c: str, d: str, e: List[str]) -> Tuple[int, int, int, int, int]:
def solve(a, b, c, d, e):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    b = input()
    c = input()
    d = input()
    e = [None for _ in range(d)]
    for i in range(d):
        e[i] = input()
    a, b, c, d, e = solve(a, b, c, d, e)
    print(a)
    print(b)
    print(c)
    print(d)
    print(e)


if __name__ == '__main__':
    main()
