#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, S: List[int], T: List[int], X: List[int], D: List[int]) -> Tuple[List[str], List[str]]:
def solve(N, Q, S, T, X, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    S = [None for _ in range(N)]
    T = [None for _ in range(N)]
    X = [None for _ in range(N)]
    D = [None for _ in range(Q)]
    for i in range(N):
        S[i], T[i], X[i] = map(int, input().split())
    for i in range(Q):
        D[i] = int(input())
    a, d = solve(N, Q, S, T, X, D)
    for i in range(N):
        print(a[i])
    for i in range(N):
        print(d[i])


if __name__ == '__main__':
    main()
