#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W = random.randint(1, 1000)  # TODO: edit here
    p = [None for _ in range(W)]
    H = random.randint(1, 1000)  # TODO: edit here
    q = [None for _ in range(H)]
    for i in range(W):
        p[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(H):
        q[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(W, H)
    for i in range(W):
        print(p[i])
    for i in range(H):
        print(q[i])


if __name__ == "__main__":
    main()
