#!/usr/bin/env python3
# from typing import *


# def solve(N: int, a: List[int], b: List[int], M: int, u: List[int], v: List[int]) -> int:
def solve(N, a, b, M, u, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = [None for _ in range(N - 1)]
    b = [None for _ in range(N - 1)]
    for i in range(N - 1):
        a[i], b[i] = map(int, input().split())
    M = int(input())
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = map(int, input().split())
    a1 = solve(N, a, b, M, u, v)
    print(a1)


if __name__ == '__main__':
    main()
