#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, X: int, Y: int) -> int:
def solve(N, K, X, Y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    K = int(input())
    X = int(input())
    Y = int(input())
    a = solve(N, K, X, Y)
    print(a)


if __name__ == '__main__':
    main()
