#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, K: int) -> Tuple[int, int]:
def solve(A, B, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, K = map(int, input().split())
    c, d = solve(A, B, K)
    print(c, d)


if __name__ == '__main__':
    main()
