#!/usr/bin/env python3
# from typing import *


def solve(N, M, C, B, A):
    count = 0
    for i in range(N):
        total = C
        for j in range(M):
            total += A[i][j] * B[j]
        if 0 < total:
            count += 1
    return count


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, C = map(int, input().split())
    B = list(map(int, input().split()))
    A = [list(map(int, input().split())) for _ in range(N)]

    a1 = solve(N, M, C, B, A)
    print(a1)


if __name__ == '__main__':
    main()
