#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, C: int, X: int) -> float:


def solve(A, B, C, X):
    if X <= A:
        return 1
    if X <= B:
        return C / (B - A)
    return 0


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, X = map(int, input().split())
    a = solve(A, B, C, X)
    print(a)


if __name__ == '__main__':
    main()
