#!/usr/bin/env python3
# from typing import *


# def solve(N: int, D: int) -> int:
def solve(N, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, D = map(int, input().split())
    a = solve(N, D)
    print(a)


if __name__ == '__main__':
    main()
