#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, C: int, D: int, E: int, F: int) -> Tuple[int, int]:
def solve(A, B, C, D, E, F):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, D, E, F = map(int, input().split())
    c, d = solve(A, B, C, D, E, F)
    print(c, d)


if __name__ == '__main__':
    main()
