#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> str:
import string


def solve(S):
    if S[0] != 'A':
        return 'WA'

    cnt = 0
    for v in S[2:-1]:
        if v == 'C':
            cnt += 1
            if 1 < cnt:
                return 'WA'
        if v != 'C' and v in string.ascii_uppercase:
            return 'WA'

    if cnt == 0 or S[1] in string.ascii_uppercase or S[-1] in string.ascii_uppercase:
        return 'WA'

    return 'AC'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
