#!/usr/bin/env python3
# from typing import *


# def solve(A: str, B: str) -> str:
def solve(A, B):
    if A > B:
        return "GREATER"

    if A < B:
        return "LESS"

    return "EQUAL"


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = int(input())
    B = int(input())
    a = solve(A, B)
    print(a)


if __name__ == '__main__':
    main()
