#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    K = random.randint(1, 1000)  # TODO: edit here
    p = [None for _ in range(K)]
    q = [None for _ in range(K)]
    L = random.randint(1, 1000)  # TODO: edit here
    r = [None for _ in range(L)]
    s = [None for _ in range(L)]
    for i in range(K):
        p[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        q[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(L):
        r[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        s[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, K, L)
    for i in range(K):
        print(p[i], q[i])
    for i in range(L):
        print(r[i], s[i])


if __name__ == "__main__":
    main()
