#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, L: int, p: List[int], q: List[int], r: List[int], s: List[int]) -> List[str]:
def solve(N, K, L, p, q, r, s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K, L = map(int, input().split())
    p = [None for _ in range(K)]
    q = [None for _ in range(K)]
    r = [None for _ in range(L)]
    s = [None for _ in range(L)]
    for i in range(K):
        p[i], q[i] = map(int, input().split())
    for i in range(L):
        r[i], s[i] = map(int, input().split())
    ans = solve(N, K, L, p, q, r, s)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
