#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: str, c: str) -> int:
def solve(a, b, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    b = input()
    c = input()
    a1 = solve(a, b, c)
    print(a1)


if __name__ == '__main__':
    main()
