#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(s: str) -> int:
def solve(s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    a = solve(s)
    print(a)


if __name__ == '__main__':
    main()
