#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int) -> int:
def solve(N, A, B):
    r = min(N % (A + B), A)
    return N // (A + B) * A + r


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    a = solve(N, A, B)
    print(a)


if __name__ == '__main__':
    main()
