#!/usr/bin/env python3
# from typing import *


# def solve(s: str) -> int:
def solve(s):
    cnt = 0
    sec = False
    max_len = 0
    for i in range(len(s)):
        if s[i] == "A" and sec == False:
            sec = True

        if sec == True:
            cnt += 1

        if s[i] == "Z" and sec == True:
            if max_len < cnt:
                max_len = cnt

    return max_len


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    a = solve(s)
    print(a)


if __name__ == '__main__':
    main()
