#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, u: List[int], v: List[int]) -> Tuple[List[str], List[str], List[str], List[str]]:
def solve(N, M, u, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = map(int, input().split())
    x, y, z, w = solve(N, M, u, v)
    for i in range(N - 1):
        print(x[i], y[i])
    for i in range(N - 1):
        print(z[i], w[i])


if __name__ == '__main__':
    main()
