#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(a: int, b: int) -> str:
def solve(a, b):
    c = int(str(a) + str(b))
    for i in range(1000):
        if c == i ** 2:
            return YES
    return NO


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    a1 = solve(a, b)
    print(a1)


if __name__ == '__main__':
    main()
