#!/usr/bin/env python3
# from typing import *


# def solve(L: int) -> Tuple[int, int, List[int], List[int], List[int]]:
def solve(L):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    L = int(input())
    c, g, h, m, n = solve(L)
    print(c, g)
    for i in range(g):
        print(h[i], m[i], n[i])


if __name__ == '__main__':
    main()
