#!/usr/bin/env python3
# from typing import *


# def solve(N: int, K: int, x: List[int], y: List[int], c: List[int]) -> float:
def solve(N, K, x, y, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    c = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i], c[i] = map(int, input().split())
    a = solve(N, K, x, y, c)
    print(a)


if __name__ == '__main__':
    main()
