#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(a: str, b: str, c: List[str]) -> int:
def solve(a, b, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    c = [None for _ in range(a)]
    b = next(tokens)
    for i in range(a):
        c[i] = next(tokens)
    assert next(tokens, None) is None
    a1 = solve(a, b, c)
    print(a1)


if __name__ == '__main__':
    main()
