#!/usr/bin/env python3
# from typing import *


# def solve(Q: int, a: List[int], b: List[int], c: List[int], d: List[int]) -> Tuple[int, int]:
def solve(Q, a, b, c, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = int(input())
    a = [None for _ in range(Q)]
    b = [None for _ in range(Q)]
    c = [None for _ in range(Q)]
    d = [None for _ in range(Q)]
    for i in range(Q):
        a[i], b[i], c[i], d[i] = map(int, input().split())
    g, h = solve(Q, a, b, c, d)
    print(g)
    print(h)


if __name__ == '__main__':
    main()
