#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
auto solve(int64_t a, int64_t b, int c, const std::vector<int64_t> &d) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t a, b;
    int c;
    std::cin >> a >> b >> c;
    std::vector<int64_t> d(c);
    REP (i, c) {
        std::cin >> d[i];
    }
    auto ans = solve(a, b, c, d);
    REP (i, a) {
        std::cout << e[i] << '\n';
    }
    return 0;
}
