#!/usr/bin/env python3
# from typing import *
from collections import defaultdict

YES = 'Yes'
NO = 'No'


# def solve(a: int, b: int, c: int, d: List[int]) -> List[str]:
def solve(N, K, Q, A):
    # -Qになる
    points = defaultdict(lambda: 0)
    for v in A:
        points[v] += 1

    for i in range(N):
        # print(K - Q + points[i])
        if 0 < K - Q + points[i + 1]:
            print("Yes")
        else:
            print("No")


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c = map(int, input().split())
    d = [None for _ in range(c)]
    for i in range(c):
        d[i] = int(input())
    solve(a, b, c, d)


if __name__ == '__main__':
    main()
