#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = random.randint(1, 1000)  # TODO: edit here
    a = [None for _ in range(A)]
    B = random.randint(1, 1000)  # TODO: edit here
    b = [None for _ in range(B)]
    M = random.randint(1, 1000)  # TODO: edit here
    x = [None for _ in range(M)]
    y = [None for _ in range(M)]
    c = [None for _ in range(M)]
    for i in range(A):
        a[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(B):
        b[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(M):
        x[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        y[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        c[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(A, B, M)
    print(*[a[i] for i in range(A)])
    print(*[b[i] for i in range(B)])
    for i in range(M):
        print(x[i], y[i], c[i])


if __name__ == "__main__":
    main()
