#include <bits/stdc++.h>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int A, int B, int M, const std::vector<int64_t> &a, const std::vector<int64_t> &b, const std::vector<int64_t> &x, const std::vector<int64_t> &y, const std::vector<int64_t> &c) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int A, B, M;
    std::cin >> A;
    std::vector<int64_t> a(A);
    std::cin >> B;
    std::vector<int64_t> b(B);
    std::cin >> M;
    std::vector<int64_t> x(M), y(M), c(M);
    REP (i, A) {
        std::cin >> a[i];
    }
    REP (i, B) {
        std::cin >> b[i];
    }
    REP (i, M) {
        std::cin >> x[i] >> y[i] >> c[i];
    }
    auto ans = solve(A, B, M, a, b, x, y, c);
    std::cout << ans << '\n';
    return 0;
}
