#!/usr/bin/env python3
# from typing import *


# def solve(N: int, D: int, X: int, A: List[int]) -> int:
def solve(N, D, X, A):
    cnt = X
    for i in range(0, N):
        days = []
        day = 1
        while True:
            if day <= D:
                days.append(day)
                day += A[i]
            else:
                break
        cnt += len(days)
    return cnt


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N)]
    D, X = map(int, input().split())
    for i in range(N):
        A[i] = int(input())
    a = solve(N, D, X, A)
    print(a)


if __name__ == '__main__':
    main()
