#!/usr/bin/env python3
# from typing import *


# def solve(c: str) -> str:
def solve(c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    c = input()
    a = solve(c)
    print(a)


if __name__ == '__main__':
    main()
