#!/usr/bin/env python3
# from typing import *


# def solve(n: int, k: int, a: List[str]) -> Tuple[List[str], str]:
def solve(n, k, a):
    print("".join(["#" for _ in range(k + 2)]))
    for v in a:
        print(f"#{v}#")
    print("".join(["#" for _ in range(k + 2)]))


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n, k = map(int, input().split())
    a = [None for _ in range(n)]
    for i in range(n):
        a[i] = input()
    solve(n, k, a)


if __name__ == '__main__':
    main()
