#!/usr/bin/env python3
# from typing import *


# def solve(S: str) -> int:
def solve(S):
    for i in range(10):
        if str(i) not in S:
            return i


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
