#!/usr/bin/env python3
# from typing import *


# def solve(n: int, a: List[int]) -> Tuple[int, int]:


def solve(a):
    print(a)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    x1, y1 = list(map(int, input().split()))
    x2, y2 = list(map(int, input().split()))
    x3, y3 = list(map(int, input().split()))

    print(x1 ^ x2 ^ x3, y1 ^ y2 ^ y3)


if __name__ == '__main__':
    main()
