#!/usr/bin/env python3
# from typing import *


# def solve(H: int, A: int) -> int:
def solve(H, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, A = map(int, input().split())
    a = solve(H, A)
    print(a)


if __name__ == '__main__':
    main()
