#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(S: str) -> str:
def solve(S):
    if S.count("N") and S.count("S") == 0 or S.count("N") == 0 and S.count("S"):
        return NO

    if S.count("W") and S.count("E") == 0 or S.count("W") == 0 and S.count("E"):
        return NO

    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
