#!/usr/bin/env python3
# from typing import *


# def solve(S: int) -> int:
def solve(S):
    ans = []
    # len(S) - 2にしておけばindex out of rangeを気にしなくてよい
    for v in range(len(S) - 2):
        ans.append(abs(753 - int(S[v] + S[v + 1] + S[v + 2])))
    return min(ans)


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)


if __name__ == '__main__':
    main()
