#!/usr/bin/env python3
# from typing import *


# def solve(N: int, T: str) -> Tuple[int, int]:
def solve(N, T):
    dir = ["N", "E", "S", "W"]
    dn = 1
    K = {"x": 0, "y": 0}
    for i in range(N):
        if (T[i] == "S"):
            # 1進む
            if (dir[dn] == "N"):
                K["y"] += 1
            if (dir[dn] == "E"):
                K["x"] += 1
            if (dir[dn] == "W"):
                K["x"] -= 1
            if (dir[dn] == "S"):
                K["y"] -= 1
        else:
            # 90度回転する
            dn += 1
            if (dn == 4):
                dn = 0
    return K["x"], K["y"]


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    T = input()
    x, y = solve(N, T)
    print(x, y)


if __name__ == '__main__':
    main()
