#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, K: int, A: List[int], B: List[int]) -> str:
def solve(N, K, A, B):
    for i in range(N - 1):
        cnt = 0
        if abs(A[i + 1] - A[i]) <= K or abs(B[i + 1] - A[i]) <= K:
            cnt += 1

        if abs(A[i + 1] - B[i]) <= K or abs(B[i + 1] - B[i]) <= K:
            cnt += 1

        if cnt == 0:
            return NO

    return YES


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(N):
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K, A, B)
    print(a)


if __name__ == '__main__':
    main()
