#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, A: List[int], B: List[int], L: List[int], R: List[int]) -> Tuple[str, List[str]]:
def solve(N, M, A, B, L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    L = [None for _ in range(M)]
    R = [None for _ in range(M)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    for i in range(M):
        L[i], R[i] = map(int, input().split())
    k, c = solve(N, M, A, B, L, R)
    print(k)
    print(*[c[i] for i in range(k)])


if __name__ == '__main__':
    main()
