#!/usr/bin/env python3
# from typing import *


def calc(A, B, C, X):
    total = 0
    cnt = 0
    break_time = 0
    is_break = False
    for i in range(1, X + 1):
        # 休憩していないときのみカウントする
        if not is_break:
            cnt += 1
            total += B
            # A歩歩いたら休憩
            if cnt == A:
                cnt = 0
                is_break = True
        else:
            # 休憩中のときは休憩時間を1ずつ増やす
            break_time += 1
            # 休憩が終了したとき
            if break_time == C:
                break_time = 0
                is_break = False
    return total


# def solve(A: int, B: int, C: int, D: int, E: int, F: int, X: int) -> str:
def solve(A, B, C, D, E, F, X):
    takahasi = calc(A, B, C, X)
    aoki = calc(D, E, F, X)

    if takahasi == aoki:
        return 'Draw'

    if takahasi < aoki:
        return 'Aoki'

    return 'Takahashi'


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, D, E, F, X = map(int, input().split())
    a = solve(A, B, C, D, E, F, X)
    print(a)


if __name__ == '__main__':
    main()
