#!/usr/bin/env python3
# from typing import *


# def solve(ABCD: str) -> str:
def solve(ABCD):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    ABCD = input()
    a = solve(ABCD)
    print(a)


if __name__ == '__main__':
    main()
