#!/usr/bin/env python3
# from typing import *


# def solve(H: int) -> int:
def solve(H):
    if H == 1:
        return 1

    cnt = 1
    ans = 0
    while 0 < H:
        ans += cnt
        H = H // 2
        cnt *= 2
    return ans


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H = int(input())
    a = solve(H)
    print(a)


if __name__ == '__main__':
    main()
