#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    x = [None for _ in range(0)]
    r = random.randint(1, 10)  # TODO: edit here
    D = random.randint(1, 10)  # TODO: edit here
    x[0] = random.randint(1, 10)  # TODO: edit here
    print(r, D, x[0])


if __name__ == "__main__":
    main()
