#!/usr/bin/env python3
# from typing import *


# def solve(r: str, D: str, x: List[str]) -> Any:
def solve(r, D, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    x = [None for _ in range(0)]
    r, D, x[0] = input().split()
    ans = solve(r, D, x)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
